# Generated by Django 5.1.2 on 2024-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('what_sells', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
